name: 'CI setup'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install Dependencies
      run: npm install --no-save
      shell: bash
